/**
 * NAPTAN Bus Stop Client
 * Loads pre-bundled Chelmsford bus stops from local JSON
 *
 * Note: The NAPTAN API doesn't support CORS, so we pre-bundle
 * the bus stop data. Run `node scripts/process-stops.js` to update.
 */

import { z } from 'zod';
import { Logger } from '@utils/logger';
import { retryWithBackoff } from '@utils/helpers';
import type { BusStop } from '@/types';
import { BusStopSchema } from '@/types';

// Schema for the JSON array
const BusStopsArraySchema = z.array(BusStopSchema);

/**
 * Fetch Chelmsford bus stops from pre-bundled JSON
 * The data is generated by scripts/process-stops.js from NAPTAN CSV
 */
export async function fetchChelmsfordBusStops(): Promise<BusStop[]> {
    Logger.info('Loading Chelmsford bus stops from local data');

    const stops = await retryWithBackoff(
        async () => {
            const res = await fetch('/bus-stops.min.json');
            if (!res.ok) {
                throw new Error(`Failed to load bus stops: ${res.status}`);
            }
            return res.json();
        },
        3,
        1000
    );

    const validated = BusStopsArraySchema.safeParse(stops);
    if (!validated.success) {
        Logger.error('Invalid bus stops data', validated.error);
        throw new Error('Invalid bus stops data');
    }

    Logger.success(`Loaded ${validated.data.length} bus stops`);
    return validated.data;
}
